"use client";

import { useMemo, useState } from "react";

type Lang = "zh" | "en";
type Text = { zh:string; en:string };
type Talk = {
  id:string; track:"native"|"vibe"; type:"观点"|"方法论"|"案例"|"工具";
  title:Text; speaker:Text; role:Text; overview:Text; core:Text[]; points:Text[];
  images?:string[]; recommended?:boolean; reason?:Text;
};

const t=(zh:string,en:string):Text=>({zh,en});
const talks:Talk[]=[
  {id:"N01",track:"native",type:"观点",title:t("智能、艺术与人机协作的底层关系","Intelligence, Art and Human–AI Collaboration"),speaker:t("分享嘉宾（现场记录未注明姓名）","Guest speaker (name not captured)"),role:t("AI 原生创新分论坛分享嘉宾","D20 AI-Native Innovation speaker"),overview:t("从生命演化与电影影像本体论出发，讨论智能是什么、艺术为何不可被纯粹计算，以及人在人机协作中的位置。","A philosophical opening on intelligence, cinematic ontology, and why human experience remains central to creation."),core:[t("分享把智能放回漫长的生命演化史中理解：复制、反应、理解、心智、语言与文字，是生命为了延续而逐层形成的能力。","Intelligence is traced through evolution—from replication and reaction to mind, language and writing."),t("AI 生成影像没有现实世界中的原型，它改变了电影影像作为现实“索引”的传统基础，也迫使创作者重新回答什么是作品。","AI imagery has no physical referent, challenging cinema’s traditional status as an index of reality."),t("演讲提出 O = (H + A) × e^(λH) 的人机协作模型。AI 提供能力，人类经验 H 则决定这种能力会被激发到什么程度。","The proposed collaboration model places human intelligence as the exponential amplifier of AI capability.")],points:[t("艺术中的空白、偶得、转向与不可言说，并不是需要消除的噪声。","Ambiguity, chance and the unsayable are not noise to be removed."),t("AI 可以模拟形式，但作品为何成立仍依赖人的生命经验与表达动机。","AI may simulate form, but human experience gives a work its reason to exist.")],images:["/d20/am-1.png"],recommended:true,reason:t("作为整场上午论坛的思想入口，它能帮助设计师先建立判断框架，再理解后续工具和工程实践。","A useful conceptual frame before entering the later tools and engineering practices.")},
  {id:"N02",track:"native",type:"观点",title:t("设计师的焦虑、品味与 Skill 封装","Anxiety, Taste and Packaging Design as Skills"),speaker:t("分享嘉宾（现场记录未注明姓名）","Guest speaker (name not captured)"),role:t("AI 产品与设计实践者","AI product and design practitioner"),overview:t("一场节奏轻快但问题尖锐的分享：当设计能力被写成 Skill、风格可以大规模调用，品味是否仍然是设计师的护城河？","A sharp discussion of what happens when taste and design capability become reusable AI skills."),core:[t("设计师的焦虑不只来自 AI，而是来自“会使用 AI 的人”。与此同时，工具学习成本正在快速下降：越晚使用，工具可能越不需要学习。","Design anxiety increasingly comes from people who use AI well, while tools themselves require less learning."),t("品味被拆分为约束与敏感性。约束可以写成规则，敏感性则来自长期经验、文化处境与对细微差异的感知。","Taste is separated into constraints and sensitivity; only the former is easily encoded."),t("当一种优秀风格被封装并被大量调用，它会迅速进入大众审美，继而成为新的默认样式。Skill 既放大品味，也可能让品味贬值。","Once a style is packaged and widely reused, it can quickly become another visual default.")],points:[t("Skill 的上限取决于编写者的认知上限。","A skill can only be as good as its author’s understanding."),t("不要只把结果写进 Skill，更要把判断与方法写进去。","Encode judgment and method, not merely outputs.")]},
  {id:"N03",track:"native",type:"案例",title:t("AIGC 影像产业：从生成繁荣到作者性回归","AIGC Film: From Generation Boom to Authorship"),speaker:t("北影节 AIGC 单元相关分享嘉宾","Representative of the BJIFF AIGC programme"),role:t("AI 影像产业观察与实践者","AI film industry practitioner"),overview:t("通过北影节 AIGC 单元三年的作品与数据，观察技术进步、审美趋同和长内容创作的真实瓶颈。","Three years of festival data reveal rapid technical gains, aesthetic convergence and the bottlenecks of long-form AI film."),core:[t("投稿量由 430 部增长至约 3000 部，作品在分辨率、微表情、口型和跨镜一致性上显著进步。","Submissions grew from 430 to roughly 3,000, with rapid gains in fidelity and consistency."),t("44.9% 的作品选择超写实风格，说明模型能力提升并不自动带来新的影像语言。大量作品只是完成生成，还没有进入创作。","44.9% of works adopted hyperrealism, showing that technical progress does not automatically create new visual language."),t("《七日浮生》把导演真实潜水事故转化为病床意识流；《牡丹记》反向利用模型幻觉。两者都回答了“为什么非 AI 不可”。","Winning works used personal experience or model hallucination in ways that made AI integral rather than incidental.")],points:[t("创造力向生成之前位移：数据、训练、清洗、选择和拒绝都属于创作。","Creativity moves upstream into data, training, selection and rejection."),t("长片的主要难题仍是人物、空间和世界观跨镜头的一致性。","Long-form work still struggles with identity, space and world consistency.")]},
  {id:"N04",track:"native",type:"方法论",title:t("从 Design 到 Build：把设计流程翻译成 Agent Loop","From Design to Build: Translating Design into an Agent Loop"),speaker:t("Code Work / AI 原生产品团队分享嘉宾","Code Work / AI-native product team"),role:t("AI 原生产品与设计工程实践者","AI-native product and design engineering practitioner"),overview:t("设计师进入真实代码库后，如何让设计系统、规则和质量检查成为 Agent 可以持续执行的机制。","How design systems, rules and quality checks become mechanisms an agent can execute continuously."),core:[t("设计师不再只交付设计稿，而是在 monorepo 中维护真实运行的设计系统 package，并直接参与产品代码。","Designers maintain executable design-system packages inside the product codebase."),t("三层体验保障包括：Agent CMD 保护核心组件，UI Check 扫描违规颜色与重复造轮子，巡检 Agent 监控绕过评审的提交。","Three safeguards protect core components, scan UI violations and monitor unreviewed changes."),t("Code Work 把设计过程拆为确认边界、制定计划、获取上下文、生成、质量门禁，以及用户的 Nudge 与 Frame。","The design process becomes a loop of boundaries, planning, context, generation, quality gates, nudge and frame.")],points:[t("AI 生成质量首先取决于代码库与设计系统是否清晰。","AI output quality starts with a clear codebase and design system."),t("设计的新边界，是为人与 Agent 之间的对齐机制而设计。","The new design boundary is the alignment mechanism between people and agents.")],images:["/d20/am-4.png","/d20/am-5.png"]},
  {id:"N05",track:"native",type:"方法论",title:t("Runtime Design 与面向 Agent 的设计资产","Runtime Design and Agent-Readable Assets"),speaker:t("千问云 / 阿里云设计团队分享嘉宾","Qwen Cloud / Alibaba Cloud Design team"),role:t("AI 原生设计语言与平台实践者","AI-native design language practitioner"),overview:t("从网页设计工具史讲到人机平权平台：未来的网站不仅要让人看懂，也要让 Agent 能读取、操作和完成任务。","A history of interface tools leading to sites that agents can read, operate and act upon."),core:[t("Token、样式、字体梯度、组件与交互原则被代码化，设计资产从图纸变成可调用的 Code Block。","Tokens, typography, components and interaction principles become callable code assets."),t("面向 Agent 的界面需要清晰语义、可访问代码、方向说明、Design.md、llm.txt 与可执行 Skill。","Agent-facing interfaces need semantics, accessible code, Design.md, llm.txt and executable skills."),t("Design in Runtime 意味着设计在真实运行环境中被组织、点击和修改，交付物本身就是可继续工作的系统。","Design in Runtime makes the deliverable an operable system rather than a static specification.")],points:[t("Human Read 与 Agent Read 不是两套产品，而是同一体验的两种阅读层。","Human Read and Agent Read are two layers of one experience."),t("作品集也将从 PDF 转向可交互、可运行的网站。","Portfolios will move from PDFs to interactive, running sites.")],images:["/d20/am-6.png"]},
  {id:"V01",track:"vibe",type:"方法论",title:t("意图驱动的 AI 设计新范式：Vibe Designing","Vibe Designing: An Intent-Driven AI Design Paradigm"),speaker:t("杨涛","Yang Tao"),role:t("阿里云 AI Native 产品设计负责人","Head of AI-Native Product Design, Alibaba Cloud"),overview:t("从 Pixels 到 Vibe：设计师不再从执行末端开始，而是从体验、调性与意图的源头定义系统。","A move from pixels to intent: designers define experience, tone and rules before generating interfaces."),core:[t("AI Coding 已从开发者的独门工具变为通识创造能力。设计师可以从使用工具走向制作自己的工具。","AI coding is becoming a general creative capability, allowing designers to build their own tools."),t("Agent 产品的体验会随用户意图实时组织。设计师不再画出所有页面，而是定义生成式 UI 的规则、边界和反馈。","Agent experiences are organized in real time; designers define rules, boundaries and feedback rather than every screen."),t("完整方法包括上下文组织、风格规约、生成、评价与迭代。作品集也应成为能承载叙事、文化理解与 AI 能力的动态网站。","The workflow combines context, style specifications, generation, evaluation and iteration.")],points:[t("设计起点从像素和图层上移到“我要什么体验”。","The starting point moves from layers to the intended experience."),t("临时界面可以变化，但生成它的体验原则必须稳定。","Interfaces may be temporary; the principles generating them must be stable.")],images:["/d20/pm-1.png"],recommended:true,reason:t("它最直接解释了设计师的工作对象正在如何变化，也与团队接下来做 AI 产品、作品集和设计系统高度相关。","It most directly explains how the designer’s object of work is changing.")},
  {id:"V02",track:"vibe",type:"案例",title:t("设计的翻译力：AI 如何进入千行百业","Design as Translation: Bringing AI into Industry"),speaker:t("王婉","Wang Wan"),role:t("阿里云政企设计负责人","Head of Government & Enterprise Design, Alibaba Cloud"),overview:t("从企业业务场景讨论设计如何翻译复杂专业知识，并把优秀项目、行业经验和解决方案沉淀为可检索资产。","How design translates specialised knowledge and turns project experience into searchable organisational assets."),core:[t("企业 AI 设计不是套用统一界面，而是理解行业语言、业务目标、使用环境和决策链，再把它们转译为产品体验。","Enterprise AI design translates industry language, goals, environments and decision chains into product experiences."),t("优秀项目库不应只是视觉参考集合，还需要保留问题、策略、方法、结果与适用条件。","A project library should retain problems, strategies, methods, outcomes and conditions—not just screenshots."),t("语义检索让设计师能从组织历史中找到相似问题和成熟解法，降低重复研究与寻找参考的成本。","Semantic retrieval helps teams recover proven solutions from organisational memory.")],points:[t("设计师的价值是跨专业语境进行准确翻译。","Designers create value by translating accurately across professional contexts."),t("知识库的检索质量，取决于沉淀时是否保留了结构和背景。","Retrieval quality depends on structure and context captured at the time of documentation.")],images:["/d20/am-3.png"]},
  {id:"V03",track:"vibe",type:"案例",title:t("弥合与生成：AI 时代传统艺术的新边界","Bridging and Generating: Traditional Art in the AI Era"),speaker:t("沈乐平","Shen Leping"),role:t("中国美术学院书法学院副院长、博士生导师","Deputy Dean, School of Calligraphy, China Academy of Art"),overview:t("以书法与篆刻工作坊为例，展示专业审美如何介入模型训练，并重新讨论传统、技术、版权和创作主体。","A calligraphy and seal-carving workshop explores professional aesthetics, model training, copyright and authorship."),core:[t("团队从北魏墓志、智永千字文、草书与颜真卿等经典范本采集高清数据，训练具有风格意识的模型。","The team collected high-resolution data from canonical works to train style-aware models."),t("难点不是生成像毛笔字的图，而是把气、韵、法、虚实相生等抽象判断转化为模型可处理的数字逻辑。","The challenge is translating concepts such as qi, rhythm and negative space into machine-processable logic."),t("项目建立作品编号、存证日期与数字身份，探索国内较早一批具备数字版权的人机共创书法作品。","The project explored digital identity and copyright for human–AI co-created calligraphy.")],points:[t("AI 是器、是客；人是魂、是主体。","AI is the instrument; the human remains the creative subject."),t("传统不是静止教条，而是在工具、社会与审美碰撞中持续更新。","Tradition is not static doctrine but a practice continually renewed through change.")],recommended:true,reason:t("它把看似距离最远的传统书法与 AI 放在一起，能刷新设计师对“创新必须抛弃传统”的惯性理解。","It challenges the assumption that innovation requires abandoning tradition.")},
  {id:"V04",track:"vibe",type:"工具",title:t("从设计资产到 OPC：让个人能力可复用、可商业化","From Design Assets to OPC"),speaker:t("AJ","AJ"),role:t("WaytoAGI 创始人","Founder, WaytoAGI"),overview:t("从产品经理和社区实践出发，讨论如何用 Design.md、知识库与 AI 分身，把风格、内容和工作流变成个人资产。","How Design.md, knowledge bases and AI doubles turn style, content and workflow into reusable personal assets."),core:[t("Design.md 可以从参考网站和既有作品中抽离品牌、颜色、组件和视觉规律，成为模型可理解的风格说明书。","Design.md extracts brand, colour, component and visual rules into a model-readable style specification."),t("个人录音、笔记和网络收藏被结构化进入知识库，作为生成内容时持续补充的上下文。","Recordings, notes and saved references become structured context for generation."),t("Demo 进入市场需要的不只是生成页面，还包括产品流程、用户验证、商业化与持续运营。OPC 强调一个人也能连接完整链路。","Taking a demo to market requires product flow, validation, commercialisation and operations—not just generation.")],points:[t("风格要成为可复用资产，内容要变得结构化。","Style should become reusable assets; content should become structured."),t("AI 降低组建团队的门槛，但执行与进入市场仍然决定结果。","AI lowers team barriers, but execution and market entry still determine outcomes.")]},
  {id:"V05",track:"vibe",type:"案例",title:t("AI 视频生成工作流：从五千条素材到四分钟成片","AI Video Workflow: 5,000 Assets to a Four-Minute Film"),speaker:t("崔一 / 抽象仔","Cui Yi / Chouxiangzai"),role:t("B站 UP 主、前央视导演、抽象世界联合创始人","Creator, former CCTV director, co-founder of Chouxiang World"),overview:t("以商业 MV 项目为例，拆解 AI 视频在人物设定、场景真实感、素材选择与团队协作中的实际成本。","A commercial music-video case revealing the real cost of character, scene, selection and team workflows."),core:[t("四分钟成片由十人团队历时近三个月完成，共生成约五千条可用素材，并消耗大量模型积分。","A ten-person team spent nearly three months and generated around 5,000 usable assets."),t("关键人物先建立四视图和造型设定；场景设计通过真实商业照片约束模型，减少古代建筑中过度规整的“AI 感”。","Character turnarounds and real photographic references constrained identity and scene realism."),t("团队重新分工为艺术概念、人物设定、造型、场景和 AI 生成导演。生成速度提升后，选择、统一和推进客户决策成为主要工作。","Roles shifted toward concept, character, styling, environment and AI generation direction.")],points:[t("AI 视频不是按下生成键，而是大规模选择与持续对齐。","AI video is large-scale selection and continuous alignment."),t("商业创作仍需要流程管理、客户沟通和一致的艺术方向。","Commercial work still demands process, communication and a coherent art direction.")]},
  {id:"V06",track:"vibe",type:"工具",title:t("从图片到 3D 与世界模型：Tripo 的能力演进","Image-to-3D and World Models: Tripo"),speaker:t("Tripo 团队分享嘉宾","Tripo team speaker"),role:t("AI 3D 产品实践者","AI 3D product practitioner"),overview:t("展示图片生成 3D 模型的能力进展，并延伸到场景生成、游戏制作与世界模型的可能性。","Progress in image-to-3D generation, extending toward scenes, game creation and world models."),core:[t("单张或多张参考图可以更快生成可编辑 3D 资产，降低角色、道具和场景原型制作门槛。","Single or multiple images can rapidly produce editable 3D assets."),t("能力从孤立模型逐步延伸到具有空间关系的完整场景，为游戏、影视和空间设计提供新的快速原型方式。","The capability is expanding from isolated objects toward spatially coherent scenes."),t("世界模型的意义不只在视觉生成，而在对空间、物体关系和可交互规则的建模。","World models represent space, object relations and interaction rules—not merely visuals.")],points:[t("3D 生成正在从资产生产走向环境构建。","3D generation is moving from asset production to environment construction."),t("对设计师而言，最直接的价值是更低成本地验证空间与叙事。","For designers, the immediate value is lower-cost spatial and narrative prototyping.")]},
];

// Official programme names, speakers and roles from the D20 sub-forum page.
const official:Record<string,{title:Text;speaker:Text;role:Text}>={
  N01:{title:t("从数据到智慧的认知阶梯","The Cognitive Ladder from Data to Wisdom"),speaker:t("杨树","Yang Shu"),role:t("中国美术学院电影学院制作系主任、中国美术家协会数字艺术艺委会副秘书长","Head of Production, School of Film, China Academy of Art")},
  N02:{title:t("AI-Native Design: Agentic UI与审美驾驭","AI-Native Design: Agentic UI and Aesthetic Direction"),speaker:t("谭啸","Tan Xiao"),role:t("阿里云创新中心高级设计专家 & 秒悟设计负责人","Senior Design Expert, Alibaba Cloud Innovation Center; Design Lead of Miaowu")},
  N03:{title:t("一场从创作到产业的深度跃迁——2026北影节AIGC单元全回顾","A Deep Leap from Creation to Industry — 2026 BJIFF AIGC Review"),speaker:t("唐俊淑","Tang Junshu"),role:t("中国传媒大学动画与数字艺术学院硕士导师 / 影视协同创作研发中心负责人 / 北京国际电影节AIGC单元负责人","Graduate Supervisor, Communication University of China; Head of BJIFF AIGC Programme")},
  N04:{title:t("从 Design 到 Build：Agent 时代体验设计的新边界","From Design to Build: New Frontiers of Experience Design in the Agent Era"),speaker:t("张明华","Zhang Minghua"),role:t("阿里云创新中心设计专家 & Qoder主设计师","Design Expert, Alibaba Cloud Innovation Center; Lead Designer of Qoder")},
  N05:{title:t("AI-Native时代的设计美学与交互体验迁移","Design Aesthetics and Interaction Migration in the AI-Native Era"),speaker:t("杜海航","Du Haihang"),role:t("阿里云创新中心高级设计专家 & 国际化设计负责人","Senior Design Expert and International Design Lead, Alibaba Cloud Innovation Center")},
  V01:{title:t("Vibe Designing：意图驱动的设计新范式","Vibe Designing: An Intent-Driven Design Paradigm"),speaker:t("杨涛","Yang Tao"),role:t("阿里云AI-Native产品设计负责人","Head of AI-Native Product Design, Alibaba Cloud")},
  V02:{title:t("设计的翻译力:解码千行百业，数智迭代跃迁","The Power of Design Translation: Decoding Industries and Digital-Intelligent Evolution"),speaker:t("王婉","Wang Wan"),role:t("阿里云政企设计负责人","Head of Government & Enterprise Design, Alibaba Cloud")},
  V03:{title:t("弥合与生成——AI时代传统艺术的新边界与新可能","Bridging and Generating — New Frontiers for Traditional Art in the AI Era"),speaker:t("沈乐平","Shen Leping"),role:t("中国美术学院书法学院副院长","Deputy Dean, School of Calligraphy, China Academy of Art")},
  V04:{title:t("OPC：一群人正在重新定义AI创作","OPC: A Community Redefining AI Creation"),speaker:t("AJ","AJ"),role:t("WaytoAGI 创始人","Founder, WaytoAGI")},
  V05:{title:t("创作者的游乐场：AI时代的审美与选择","The Creator’s Playground: Aesthetics and Choice in the AI Era"),speaker:t("抽象仔 XEIIZO","Chouxiangzai XEIIZO"),role:t("B站知名UP主、前央视导演、AIGC技术流抽象代表人物、全球短剧榜榜首创作者","Bilibili creator, former CCTV director and AIGC filmmaker")},
  V06:{title:t("从Vibe到Pipeline：AI 3D时代的设计全流程重构","From Vibe to Pipeline: Rebuilding the AI 3D Design Workflow"),speaker:t("朱瓜瓜","Zhu Guagua"),role:t("VAST 品牌视觉负责人","Head of Brand Visuals, VAST")},
};
talks.forEach(x=>Object.assign(x,official[x.id]||{}));
talks.find(x=>x.id==="N01")!.recommended=false;

// The transcript carries substantially more context than the index card. Keep it in the detail view.
Object.assign(talks.find(x=>x.id==="N01")!,{core:[
  t("分享从《人工智能艺术原理》课程展开，先把“人工”与“智能”拆开。智能不是某个模型突然拥有的能力，而是生命为了延续逐层形成的认知阶梯：复制、反应、理解、心智、语言，直到文字把经验跨越时间保存下来。","The talk begins with the course Principles of AI Art and frames intelligence as an evolutionary ladder."),
  t("电影 130 年的美学建立在摄影影像本体论上：镜头拍到的东西曾经真实存在，影像是现实留下的索引。AI 生成影像没有现实原型，这使电影第一次大规模面对一种“没有被拍摄过”的视觉世界。","AI imagery breaks cinema’s traditional indexical relationship with physical reality."),
  t("现场播放的学生作品《恐鸟》把生物大灭绝、智能演化与人类处境连接起来。作品的价值不在于证明模型能生成画面，而在于它用 AI 讨论了一个无法被普通拍摄替代的命题。","The student work Moa used AI to connect extinction, intelligence and the human condition."),
  t("演讲把艺术追溯到约五万年前。艺术的核心不是精确复现，而是生命感、情绪和不可言说的经验。树叶间的空隙、创作过程中的停顿、偶得与转向，都不是应当被流程消除的噪声。","Art is located in life, emotion, pauses and chance rather than pure replication."),
  t("最后以 O = (H + A) × e^(λH) 描述人机协作。AI 能力与人的能力不是简单相加，人的经验、意图和感受会指数级改变输出；人仍然决定作品要表达什么，以及什么结果值得被保留。","The collaboration model places human experience as the exponential amplifier of AI capability.")],points:[t("AI 生成影像改变了电影影像必须指向现实的传统前提。","AI imagery changes cinema’s traditional relation to reality."),t("艺术中的随机、停顿与不可言说，是创作的一部分。","Chance, pauses and the unsayable are part of creation."),t("人的经验和意图决定 AI 能力最终被用于什么。","Human experience and intention determine what AI capability is used for.")],images:["/d20/am-1.png","/d20/am-2.png"]});
Object.assign(talks.find(x=>x.id==="N02")!,{core:[
  t("谭啸从设计师对 AI 的焦虑谈起：真正带来压力的往往不是工具本身，而是能把工具更快变成产品的人。与此同时，工具的工程层越来越厚，操作越来越自然，“学得越晚，越不用学”成为一种现实趋势。","The talk begins with design anxiety and the rapidly falling operational cost of AI tools."),
  t("秒悟支持用户通过自然语言创建应用，并继续完成域名、登录与发布。它把传统上依赖开发协作的最后环节一并纳入，让设计师可以更直接地把意图变成可分享的真实产品。","Miaowu extends natural-language creation into domains, authentication and deployment."),
  t("分享把品味拆为“约束”与“敏感性”。约束可以被规则化，敏感性则来自长期经验：它让设计师发现一个结果虽然满足规则，却仍然不准确、不自然或不属于当前语境。","Taste combines codifiable constraints with sensitivity grounded in experience."),
  t("当优秀风格被封装成 Skill 并被大量调用，它会迅速进入大众审美，最终成为新的默认样式。这解释了为什么 AI 作品越来越精致，却也越来越相似。","Widely reused style skills can become a new default aesthetic."),
  t("关于 Skill 的实践建议包括：核心逻辑应亲手编写；传递方法而不只是成品；警惕历史经验固化成限制；让真实项目持续检验 Skill。个人认知最终决定了 Skill 的上限。","Skill-building principles emphasise authored logic, transferable method and real-world testing.")],points:[t("AI 可以执行约束，但无法自动获得设计师的敏感性。","AI can execute constraints but does not automatically acquire sensitivity."),t("风格被规模化复用后，可能快速变成默认审美。","Scaled reuse can quickly turn a style into a default."),t("Skill 的上限来自编写者理解问题的深度。","A skill’s ceiling comes from the author’s depth of understanding.")],images:["/d20/am-3.png"]});
Object.assign(talks.find(x=>x.id==="V01")!,{core:[
  t("杨涛先把 AI Coding 定义为新的通识创造能力。团队中的设计师不只用现有工具，而是为自己的具体问题制作小工具、发布代码包，并把一次个人尝试变成其他人可复用的能力。","AI coding is framed as a general creative capability, allowing designers to build and share tools."),
  t("Vibe Designing 的起点不是像素、图层和栅格，而是“我要什么体验、什么调性”。设计师先定义意图，再把模糊的感受翻译成模型能理解的上下文、规则与评价标准。","Vibe Designing starts from intended experience and tone rather than pixels and layers."),
  t("Agent 产品的界面会根据用户意图实时组织。过去设计信息架构与固定流程，今天则要设计动态交互、生成式 UI 和系统如何举一反三。设计师交付的是组织体验的规则，而不是穷举所有页面。","Agent interfaces are organised in real time, shifting design from fixed screens to generative rules."),
  t("为了让 AI 更接近预期，需要把设计系统从 only for humans 推进到 for both human and AI。组件、Token、语义、交互原则和设计说明要同时可被人阅读，也可被 Agent 调用。","Design systems must become readable by both humans and agents."),
  t("演讲最后把变化落到作品集：设计师仍然用作品说话，但未来的作品不再只是 PDF，而是一个可以交互的动态网站，凝聚文化理解、叙事、品味和使用 AI 的能力。","The talk concludes that portfolios should become interactive sites rather than static PDFs.")],points:[t("设计起点从执行末端上移到体验意图。","The starting point moves upstream from execution to experience intent."),t("生成式界面可以变化，生成它的原则必须清晰。","Generated interfaces may vary, but their principles must be clear."),t("设计系统需要同时服务 Human Read 与 Agent Read。","Design systems must support both Human Read and Agent Read.")]});
Object.assign(talks.find(x=>x.id==="V03")!,{core:[
  t("沈乐平先用书法史说明传统从未停止变化：从甲骨金文、秦代统一文字、汉代隶变，到魏晋风度、唐代法度、宋人尚意和清代碑学，工具、社会与审美不断推动书法突破边界。","The talk begins by showing that calligraphy has always evolved through tools, society and aesthetics."),
  t("在 AI 时代，难点不是让模型生成“像毛笔字”的图，而是让它理解长与变、雅与俗、正与奇，以及气、韵、法等传统美学中指向并不完全确定的概念。","The challenge is not brush-like imagery but translating nuanced aesthetic judgment into computational logic."),
  t("中国美院书法学院与阿里云设计中心发起工作坊，从北魏墓志、智永千字文、草书与颜真卿等经典范本采集高清数据，进行风格训练和杂糅实验，模拟传统学习中的取法路径。","The workshop trained and blended styles using high-resolution data from canonical works."),
  t("篆刻实验从数千方古代汉印中采集数据，完成模型训练和风格迁移。生成结果不仅模拟文字和章法，也尝试表现冲刀、切刀、残破，以及计白当黑、虚实相生的语言特质。","Seal-carving experiments modelled composition, cutting traces, erosion and negative space."),
  t("演讲明确区分主客：AI 是器、是客，擅长数据与运算；人是魂、是主体，负责气韵、心性、意境、生命体感和最终审美甄别。技术帮助进入经典，但探索未知仍然属于人。","AI is the instrument; the human remains the subject responsible for judgment and exploration."),
  t("项目还建立版数编号、存证日期与数字身份，探索人机共创书法的数字版权。它不仅是作品实验，也同时涉及创作、理论和教学方法的更新。","The project also explored digital identity and copyright across creation, theory and education.")],points:[t("传统书法一直在变化，AI 是新的工具变量而不是传统的终点。","AI is a new tool in a tradition that has always evolved."),t("专业审美必须进入数据采集、训练与结果甄别。","Professional aesthetics must guide data, training and evaluation."),t("AI 是器，人是主体；人的任务是判断并探索未知。","AI is the instrument; humans judge and explore the unknown.")],images:["/d20/am-1.png","/d20/am-2.png"]});

talks.push(
  {id:"V00",track:"vibe",type:"观点",title:t("GO Vibe Designing！","GO Vibe Designing!"),speaker:t("王路平","Wang Luping"),role:t("阿里云设计中心总监","Director, Alibaba Cloud Design Center"),overview:t("云智能专场开场：当 AI 从工具走向伙伴、从执行走向共创，设计进入由意图、感觉与生成共同驱动的新阶段。","Opening remarks for the Cloud Intelligence track."),core:[t("王路平回顾过去三年从 AIGC、Workflow 到 Agentic AI 的变化。AI Coding 不再只是工程能力，而逐渐成为设计师参与创造与构建产品的通识工具。","The opening traces the shift from AIGC and workflows to agentic AI."),t("论坛以 Vibe Designing 为线索，关注设计师如何表达意图、组织动态体验，并在 AI 介入之后重新定位自己的工作边界。","The forum focuses on intention, dynamic experience and changing design boundaries.")],points:[t("AI 从执行工具转向协作伙伴。","AI is moving from execution tool to collaborative partner."),t("设计的关注点从固定结果转向意图与生成过程。","Design shifts from fixed outputs to intention and generation.")]},
  {id:"V07",track:"vibe",type:"案例",title:t("AI原住民：13岁少年的创作与梦想","AI Native: A 13-Year-Old Creator’s Work and Dreams"),speaker:t("吕思彤","Lü Sitong"),role:t("13岁独立开发者","13-year-old independent developer"),overview:t("从灵感到近百件作品，一位 AI 原住民分享超过 4000 小时的学习、项目创作与对未来人机关系的想象。","A young independent developer shares over 4,000 hours of learning and nearly 100 projects."),core:[t("分享从个人进入 AI 领域的路径开始：不是先掌握完整技术体系，而是在真实兴趣和项目目标中持续学习、制作与修正。","The journey began through interests and projects rather than a complete technical curriculum."),t("近百件作品说明低门槛工具如何扩大青少年的创造范围，也提醒设计师观察下一代对代码、产品和 AI 协作的天然理解。","Nearly 100 works show how accessible tools expand young creators’ range."),t("她对未来的想象并不止于更强的生成能力，而是 AI 如何进入学习、生活与社会协作。","Her vision extends beyond generation into learning, life and social collaboration.")],points:[t("AI 原住民把模型视为自然的创作环境。","AI natives treat models as a natural creative environment."),t("持续行动和作品积累比年龄或职业边界更重要。","Sustained making matters more than age or professional boundaries.")]},
  {id:"V08",track:"vibe",type:"观点",title:t("对谈：AI 时代的“一人公司”的审美表达与商业逻辑","Dialogue: Aesthetic Expression and Business Logic of the One-Person Company"),speaker:t("刘飞 × AJ × 抽象仔 XEIIZO","Liu Fei × AJ × Chouxiangzai XEIIZO"),role:t("产品经理、播客主理人 × WaytoAGI 创始人 × AI影视创作者","Product manager and podcaster × WaytoAGI founder × AI filmmaker"),overview:t("围绕 OPC 的商业潜力、生态支持、创作边界与个人资产展开的圆桌讨论。","A roundtable on the commercial potential, support systems and creative boundaries of OPCs."),core:[t("讨论区分了 OPC 与传统自由职业者：重点不只是一个人完成更多工作，而是一个人能否搭建由 AI、工具、流程和外部服务组成的完整系统。","The panel distinguishes an OPC from freelancing through system-building."),t("当执行成本下降，市场更看重能否迅速验证并持续行动。想法本身不再稀缺，把想法推进到用户、产品和商业结果的执行力更重要。","As execution costs fall, rapid validation and sustained action become more valuable."),t("面向所有人的通用产品越来越难。模块化、定制化和围绕具体人群构建的小产品，可能更适合个人公司进入市场。","Modular products for specific audiences may suit OPCs better than universal products."),t("圆桌反复回到个人资产：风格、知识、内容、用户关系和工作流需要持续沉淀，而不是每个项目结束后重新归零。","The discussion repeatedly returns to accumulating style, knowledge, audience and workflow assets.")],points:[t("OPC 的核心是编排系统，不是一个人承担所有劳动。","OPC is about orchestrating a system, not doing every task alone."),t("执行、验证与资产沉淀比单个创意更重要。","Execution, validation and asset accumulation outweigh isolated ideas."),t("更具体、更模块化的产品可能更适合个人公司。","Specific and modular products may be better suited to OPCs.")]}
);

const ui={zh:{title:"7.11 D20｜原生创新 × Vibe Designing",sub:"两场分论坛整理",intro:"本页面整理了我在 7 月 11 日参与的两场分享：上午「AI 原生创新」与下午「云智能 / Vibe Designing」。通过场次、主题和内容类型快速浏览，也可以进入每个分享的详情，补齐核心内容与现场案例。",index:"分享目录",search:"搜索主题、分享人或观点…",all:"全部",native:"AI 原生创新",vibe:"云智能 / Vibe Designing",recommend:"推荐",why:"为什么推荐",back:"返回目录",core:"核心内容",points:"关键观点",images:"相关图片",map:"设计对象如何迁移",past:"过去",now:"现在",happening:"正在发生"},en:{title:"7.11 D20 | AI-Native × Vibe Designing",sub:"Notes from two sub-forums",intro:"This page documents the two sessions I attended on 11 July: AI-Native Innovation in the morning and Cloud Intelligence / Vibe Designing in the afternoon. Browse by track, topic and content type, then open any talk for full context and cases.",index:"Talk Index",search:"Search topics, speakers or ideas…",all:"All",native:"AI-Native Innovation",vibe:"Cloud Intelligence / Vibe Designing",recommend:"Recommended",why:"Why it matters",back:"Back to index",core:"Core content",points:"Key takeaways",images:"Related images",map:"How the object of design is shifting",past:"Past",now:"Now",happening:"Emerging"}};

export default function Home(){
  const [lang,setLang]=useState<Lang>("zh"); const [track,setTrack]=useState("all"); const [kind,setKind]=useState("全部"); const [query,setQuery]=useState(""); const [selected,setSelected]=useState<string|null>(null); const U=ui[lang];
  const shown=useMemo(()=>talks.filter(x=>(track==="all"||x.track===track)&&(kind==="全部"||x.type===kind)&&`${x.title.zh}${x.title.en}${x.speaker.zh}${x.overview.zh}${x.core.map(y=>y.zh)}`.toLowerCase().includes(query.toLowerCase())),[track,kind,query]);
  const talk=selected?talks.find(x=>x.id===selected):null;
  if(talk)return <main className="talk-page"><div className="detail-top"><button onClick={()=>setSelected(null)}>← {U.back}</button><button className="lang" onClick={()=>setLang(lang==="zh"?"en":"zh")}>{lang==="zh"?"EN":"中文"}</button></div><header className="talk-hero"><div><span>{talk.id} / {talk.track==="native"?U.native:U.vibe}</span>{talk.recommended&&<b>{U.recommend}</b>}</div><h1>{talk.title[lang]}</h1><div className="speaker"><p>{talk.speaker[lang]}</p><span>{talk.role[lang]}</span></div><p className="overview">{talk.overview[lang]}</p></header><section className="story"><div><span>01 / {U.core}</span>{talk.core.map((p,i)=><p className="story-p" key={i}>{p[lang]}</p>)}</div><aside><span>02 / {U.points}</span><ol>{talk.points.map((p,i)=><li key={i}>{p[lang]}</li>)}</ol>{talk.reason&&<div className="recommend"><b>{U.recommend} · {U.why}</b><p>{talk.reason[lang]}</p></div>}</aside></section>{talk.images&&<section className="gallery"><span>03 / {U.images}</span><div>{talk.images.map((src,i)=><figure key={src}><img src={src} alt="现场分享图片"/><figcaption>{talk.id} / IMAGE {String(i+1).padStart(2,"0")}</figcaption></figure>)}</div></section>}<footer><div><b>D20 FIELD NOTES</b><br/>{talk.track==="native"?U.native:U.vibe}</div><div>{talk.speaker[lang]}<br/>{talk.role[lang]}</div><div className="green">READ / QUESTION / REFRAME</div></footer></main>;
  return <main><header className="masthead"><div className="topline"><span>D20 / 2026</span><span>AI 设计 · 新应用</span><button className="lang" onClick={()=>setLang(lang==="zh"?"en":"zh")}>{lang==="zh"?"EN":"中文"}</button></div><div className="hero-grid"><div className="issue">FIELD<br/>NOTES<br/><b>№ 01</b></div><div><p className="eyebrow">{U.sub}</p><h1>{lang==="zh"?<>7.11 D20<br/><i>原生创新 × Vibe Designing</i></>:<>7.11 D20<br/><i>AI-Native × Vibe Designing</i></>}</h1></div><div className="abstract"><div className="orb"/><p>AI-NATIVE / AM<br/>VIBE DESIGNING / PM</p></div></div><div className="intro"><p>{U.intro}</p><p>{talks.length} TALKS · 2 TRACKS<br/>HANGZHOU / 2026.07.11</p></div></header><section className="archive" id="archive"><div className="archive-head"><div><span>01 / TALK INDEX</span><h2>{U.index}</h2></div><div className="result">{String(shown.length).padStart(2,"0")} / {talks.length}</div></div><div className="controls"><label className="search"><span>SEARCH</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={U.search}/></label><div className="filter wide"><span>TRACK / 场次</span><div><button className={track==="all"?"active":""} onClick={()=>setTrack("all")}>{U.all}</button><button className={track==="native"?"active":""} onClick={()=>setTrack("native")}>{U.native}</button><button className={track==="vibe"?"active":""} onClick={()=>setTrack("vibe")}>{U.vibe}</button></div></div><div className="filter"><span>TYPE / 类型</span><div>{["全部","观点","方法论","案例","工具"].map(x=><button className={kind===x?"active":""} onClick={()=>setKind(x)} key={x}>{lang==="en"&&x==="全部"?"All":x}</button>)}</div></div></div><div className="cards">{shown.map(item=><article className="card" key={item.id}><button className="card-main" onClick={()=>setSelected(item.id)}><span className="num">({item.id})</span><span className="meta">{item.track==="native"?U.native:U.vibe}<br/><b>{item.type}</b></span><span className="copy"><span className="speaker-line">{item.speaker[lang]} · {item.role[lang]}</span><h3>{item.title[lang]}</h3><p>{item.overview[lang]}</p>{item.recommended&&<strong className="pick">✳ {U.recommend}</strong>}</span><span className="toggle">→</span></button></article>)}</div></section><section className="map"><span>02 / SHIFT MAP</span><h2>{U.map}</h2><div className="map-grid"><div><b>{U.past}</b><h3>Pixels</h3><p>Layers · Pages · Static handoff</p></div><i>→</i><div><b>{U.now}</b><h3>Intent</h3><p>Context · Direction · Dynamic UX</p></div><i>→</i><div className="future"><b>{U.happening}</b><h3>Runtime</h3><p>Rules · Skill · Agent · Validation</p></div></div></section><footer><div><b>D20 FIELD NOTES</b><br/>{U.sub}</div><div>AI-NATIVE INNOVATION / AM<br/>VIBE DESIGNING / PM</div><div className="green">READ / QUESTION / REFRAME</div></footer></main>;
}
